version: '3.8'
name: cmc
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: huggingface_service
    ports:
      - "${PORT}:8000"  # Read the port from .env
    environment:
      - ENV=production
      - PORT=${PORT}
      - MODEL_NAME=intfloat/multilingual-e5-large
    volumes:
      - .:/app
    networks:
      - huggingface_network

networks:
  huggingface_network:
    driver: bridge
