version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    container_name: huggingface_service_gpu
    ports:
      - "${PORT}:8700"  # Read the port from .env
    environment:
      - ENV=production
      - PORT=${PORT}
      - MODEL_NAME=intfloat/multilingual-e5-large
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - huggingface_network

networks:
  huggingface_network:
    driver: bridge
