version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: huggingface_service_gpu
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=intfloat/multilingual-e5-large
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - huggingface_network

networks:
  huggingface_network:
    driver: bridge
